version: '3'
services:
  angular-app:
    build: .
    ports:
      - "4200:80"
    networks:
      - app-network
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

networks:
  app-network: